Sheet To Objects update
josdeweger-zz/SheetToObjects pull request #1
Opened 2018-05-11 14:45 UTC by Frankvanderlinden

New features:

Csv input by stream
Support for mapping based on: headername, letter (A,B,C), columnIndex, or propertname
Support for attributes(modelconfig, collumnmapping, and validation)  on the Model, see ProfileModel as example

Sorry for the huge commit ;)

2018-05-11 20:35 UTC, josdeweger-zz requested changes

2018-05-11 20:35 UTC, josdeweger-zz commented on src/SheetToObjects.Adapters.Csv/DataExtensions.cs
> +            return rowData.Select((cellData, columIndex) => new Cell(rowIndex+1, columIndex, cellData)).ToList();
When the whole thing was column letter based, I intended to use A as first column, and 1 as first row. Now that we have moved to headers (which is a great idea and should be the default imho), we can do an index starting at zero.

2018-05-11 20:35 UTC, josdeweger-zz commented on src/SheetToObjects.ConsoleApp/CsvApp.cs
> +            var fileStream = File.Open(@"C:\Users\frank.vanderlinden\Documents\Landal\homeownerimport csv\account_2.csv", FileMode.Open);
can we add a test csv to the project and use relative paths?

2018-05-11 20:35 UTC, josdeweger-zz commented on src/SheetToObjects.ConsoleApp/Models/ProfileModel.cs
> +        [IsRequired]
I like this additional feature, might come more natural to some developers! Are we mixing 'normal' configuration and 'attribute' configuration? If not, is configuration validation an option?
Can you also update the readme file?

2018-05-11 20:35 UTC, josdeweger commented on src/SheetToObjects.Lib/CellValueParser.cs
> +            if (value.IsNull())
twice the same check?

2018-05-11 20:35 UTC, josdeweger commented on src/SheetToObjects.ConsoleApp/ServiceConfigurator.cs
>                  var sheetMapper = new SheetMapper();
Do we need the comments, or can this be removed?

2018-05-11 20:35 UTC, josdeweger commented on src/SheetToObjects.ConsoleApp/ServiceConfigurator.cs
> +            //serviceCollection.AddTransient<GoogleSheetsApp>();
why is this removed?

2018-05-11 20:35 UTC, josdeweger commented on src/SheetToObjects.Core/StringExtensions.cs
> +            return value.Select((c, i) =>
now thís justifies a comment!

2018-05-11 20:35 UTC, josdeweger commented on src/SheetToObjects.Lib/Configuration/ColumnMappings/IndexColumnMapping.cs
> +        public override string DisplayName => "Column (6)";
what does this mean?

2018-05-11 20:35 UTC, josdeweger commented on src/SheetToObjects.Specs/Lib/SheetMapperSpecs.cs
> +                    .Columns(columns => columns.Add(column => column.WithHeader("Boolean").MapTo(t => t.BoolProperty))).Object())
The .Object() is not an improvement imho, especially not in terms of readability when fluently building a config. Can this be solved differently. What is this Object btw?

2018-05-11 20:35 UTC, josdeweger commented on src/SheetToObjects.Lib/IParseCellValue.cs
> +    public interface IParseValue
Can we change this into IParseCellValue and pass the actual Cell to both methods?

2018-05-12 10:06 UTC, josdeweger commented on src/SheetToObjects.Specs/Lib/Validation/RequiredRuleSpecs.cs
> +            var result = new RequiredRule(true).Validate(value);
Can we instead of using a boolean flag (which is not explicit) use something like `new RequiredRule().AllowWhiteSpace()`?

2018-05-12 10:08 UTC, josdeweger commented on src/SheetToObjects.ConsoleApp/ServiceConfigurator.cs
> +                //sheetMapper.For<ProfileModel>(cfg => cfg.Columns));
Do we still need this?

2018-05-12 10:13 UTC, josdeweger commented on src/SheetToObjects.Lib/SheetMapper.cs
> +        private void SetHeaderIndexesInColumnMappings(Row firstRow, MappingConfig mappingConfig)
I don't like the fact that the mappingConfig parameter is altered in this method. Can we return a new mappingConfig instead?

2018-05-12 10:15 UTC, josdeweger commented on src/SheetToObjects.Lib/SheetMapper.cs
> +            {
I think this class, and particularly this method, is doing to much (SRP). I suggest we move the retrieving/altering of the mapping config to a new class

2018-05-12 10:18 UTC, josdeweger-zz commented on src/SheetToObjects.Lib/Configuration/MappingConfigBuilder.cs
> +            var columnsBuilder = new ColumnsMappingBuilder<TModel>(_mappingConfig);
This is not used anymore?

2018-05-12 10:25 UTC, josdeweger commented on src/SheetToObjects.Lib/SheetMapper.cs
> +        private void SetHeaderIndexesInColumnMappings(Row firstRow, MappingConfig mappingConfig)
(and move this to the new class)

2018-05-12 21:51 UTC, Frankvanderlinden commented
Just did a commit that changed the errorvalidation. I also fixed a lot of your comments in this pull request allready and worked on the unit test coverage. You can check and improve where needed, you know how to push to my dev!

2018-05-13 10:04 UTC, josdeweger-zz approved these changes

2018-05-13 10:05 UTC, merged